### PR TITLE
Last migration fix

### PR DESCRIPTION
**Pull request by alexz429**
resolves https://github.com/uwcsc/codeybot/issues/92

resolved conflicts between master and migration branches (no real changes to frontend interactions, all backend bug fixes incorporated)

Last check of features, a few bug fixes.

### CODE REVIEW

**Review by marko-polo-cheno — CHANGES_REQUESTED** [review]
whats the github action issues in the suggestionsList file?
delete?

**Comment by marko-polo-cheno** [comment]
also, plz redo screenshots of ur user profile, get interviewers, one game o black jack, and list suggestions
so ik it works 😅

**Review by marko-polo-cheno — APPROVED** [review]
based on testing done in ur channel, looks good to me

**Comment by alexz429** [comment]
image
image
image
image
image
image
image
image

**Pull request merged**
